# docker-compose.yml - UH Groupings - dev environment

services:

  groupings-api:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - "8081:8081"
    volumes:
      - ${GROUPINGS_API_DIR}:/app/groupings  # Hot reload directory
      - ${GROUPINGS_OVERRIDES}:/overrides
    environment:
      - SPRING_PROFILES_ACTIVE=localhost
      - VAULT_SECRET_JSON=${VAULT_SECRET_JSON}
      - VAULT_SECRET_KEY=${VAULT_SECRET_KEY}

  groupings-ui:
    build:
      context: .
      dockerfile: Dockerfile-ui
    ports:
      - "8080:8080"
    volumes:
      - ${GROUPINGS_UI_DIR}:/app/groupings  # Hot reload directory
      - ${GROUPINGS_OVERRIDES}:/overrides
    environment:
      - SPRING_PROFILES_ACTIVE=localhost
