# docker-compose.yml - UH Groupings - dev environment

services:

  base-image:
    build:
      context: .
      dockerfile: Dockerfile-base
    image: groupings-base-image
    command: /bin/sh -c "echo 'Groupings project base image built using Rocky Linux 9, OpenJdk 17.'"

  groupings-api:
    build:
      context: .
      dockerfile: Dockerfile-api
    depends_on:
      - base-image
    ports:
      - "8081:8081"
    volumes:
      - ${GROUPINGS_API_DIR}:/app/groupings  # Hot reload directory
      - ${GROUPINGS_OVERRIDES}:/overrides
    environment:
      - SPRING_PROFILES_ACTIVE=localhost
      - VAULT_SECRET_JSON=${VAULT_SECRET_JSON}
      - VAULT_SECRET_KEY=${VAULT_SECRET_KEY}

  groupings-ui:
    build:
      context: .
      dockerfile: Dockerfile-ui
    depends_on:
      - groupings-api
    ports:
      - "8080:8080"
    volumes:
      - ${GROUPINGS_UI_DIR}:/app/groupings  # Hot reload directory
      - ${GROUPINGS_OVERRIDES}:/overrides
    environment:
      - SPRING_PROFILES_ACTIVE=localhost