# docker-compose.yml - UH Groupings - dev environment

services:
  groupings-api:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - "8081:8081"
    volumes:
      - ${GROUPINGS_API_SRC}:/app  # Mount the source code directory
    environment:
      - SPRING_PROFILES_ACTIVE=localhost

#  groupings-ui:
#    build:
#      context: .
#      dockerfile: Dockerfile-ui
#    ports:
#      - "8080:8080"
#    volumes:
#      - ${GROUPINGS_UI_SRC}:/app
#    environment:
#      - SPRING_PROFILES_ACTIVE=localhost
