# docker-compose.yml - UH Groupings - dev environment

# The Build script will invoke Docker to build this stack.

services:

  groupings-base:
    build:
      dockerfile: Dockerfile-base
    image: groupings-base-image
    command: /bin/sh -c "echo 'Groupings project base image - built using Rocky Linux 9, OpenJdk 17.'"

  groupings-api:
    build:
      dockerfile: Dockerfile-api
    depends_on:
      - groupings-base
    ports:
      - "8081:8081"
    volumes:
      - ${GROUPINGS_API_DIR}:/app/groupings  # Hot reload directory
      - ${GROUPINGS_OVERRIDES}:/overrides
    environment:
      - SPRING_PROFILES_ACTIVE=localhost
      - VAULT_SECRET_JSON=${VAULT_SECRET_JSON}
      - VAULT_SECRET_KEY=${VAULT_SECRET_KEY}

  groupings-ui:
    build:
      dockerfile: Dockerfile-ui
    depends_on:
      - groupings-api
    ports:
      - "8080:8080"
    volumes:
      - ${GROUPINGS_UI_DIR}:/app/groupings  # Hot reload directory
      - ${GROUPINGS_OVERRIDES}:/overrides
    environment:
      - SPRING_PROFILES_ACTIVE=dockerhost
      - HEALTH_CHECK_URL="http://groupings-api:8081/uhgroupingsapi/api/groupings/v2.1/"
      - HEALTH_CHECK_INTERVAL=30   # Interval between retries in seconds
      - HEALTH_CHECK_TIMEOUT=10    # Timeout for each curl command in seconds
      - HEALTH_CHECK_RETRIES=5     # Number of retries before giving up